[project]
authors = [ "Project AIRI Team <neko@moeru.ai>" ]
channels = [ "conda-forge" ]
name = "sherpa-onnx-demo"
platforms = [
  "osx-arm64",
  "linux-aarch64",
  "linux-64"
]
version = "0.1.0"

[tasks]
start = { cmd = [
  "python",
  "app.py"
] }

[dependencies]
python = "3.12.*"
pip = ">=25.0.1,<26"

[pypi-dependencies]
sherpa-onnx = "==1.12.14"
soundfile = "==0.12.1"
scipy = "==1.13.1"
numpy = "==1.26.4"
websockets = "==13.0.1"
fastapi = ">=0.115.12, <0.116"
uvicorn = ">=0.34.1, <0.35"
pydantic = ">=2.11.3, <3"
pydantic-core = ">=2.33.1, <3"

[feature.cuda]
platforms = [
  "linux-64",
  "win-64"
]
channels = [
  "nvidia",
  "conda-forge",
  { channel = "pytorch", priority = -1 }
]

[feature.cuda.pypi-options]
index-url = "https://pypi.org/simple"
find-links = [ { url = "https://k2-fsa.github.io/sherpa/onnx/cuda-cn.html" } ]

[feature.cuda.pypi-dependencies]
onnxruntime-gpu = "==1.19.2"
sherpa-onnx = "==1.12.14+cuda12.cudnn9"

[feature.cuda.system-requirements]
cuda = "12"

[feature.cuda.dependencies]
cuda-libraries-dev = "*"
cuda-nvcc = "*"
cuda-nvtx = "*"
cuda-cupti = "*"
cuda = "12.*"
cudnn = ">=9.0,<10"

[environments]
cuda = [ "cuda" ]
